# =========================================
#         McDis-RCON Configuration
# =========================================

### Application designed to stream the Minecraft console to Discord. This has been tested on Ubuntu 22.04.3 LTS.
### - Servers         :   Vanilla, Fabric, Paper, etc...
### - Networks        :   Waterfall, Bungeecord, or Velocity

### start_command     :   Start command for the process, e.g.: java -Xms6G -Xmx6G -Dfile.encoding=UTF-8 -jar <launcher>.jar nogui
### stop_command      :   Command to stop the process
### relay_blacklist   :   List of terms; if contained in the log, it will not be sent to Discord
### 
### If you are using MCDReforged, you must set 'advanced_console' to False in the MCDR config.
 
### Recommended terms for the relay blacklist
### - 'Changed the block at'            # Prevents spam when pasting litematics or using WorldEdit
### - 'Successfully filled'             # Prevents spam when pasting litematics or using WorldEdit
### - '[WARN]:'                         # Prevents lag warning spam
### - '~[server-intermediary.jar:?]'    # Prevents spam when doing update suppression

### To apply the changes, you must restart McDis!!!

### Description   : The bot token that will be used to initialize McDis
Bot Token:

### Description   : The ID of the channel where the McDis panel will be created
Panel ID:

### Description   : Language that McDis will use.
### Valid Values  : [en, es]
### Default Value : en
Language: en

### Description   : Number of backups that McDis will save.
### Valid Values  : [1, 5] (inclusive)
### Default Value : 3
Backups: 3

### Description   : Flask configuration
Flask:
  Allow : false
  IP    : '0.0.0.0'
  Port  : 8000

Processes:
  Networks: 
    network 1:
      start_command: start
      stop_command: end
      relay_blacklist: 
        - 'example 1'
        - 'example 2'
        - 'example 3'

  Servers:
    server 1:
      start_command: start
      stop_command: stop
      relay_blacklist: 
        - 'example 1'
        - 'example 2'
        - 'example 3'
    
    server 2:
      start_command: start
      stop_command: stop
      relay_blacklist: 
        - 'example 1'
        - 'example 2'
        - 'example 3'