# =========================================
#         McDis-RCON Configuration
# =========================================

### Application designed to stream the Minecraft console to Discord.
###
### Designed to run on Ubuntu 22.04.3 LTS and for
### - Servers         : Vanilla
### - Networks        : Waterfall, Bungeecord, or Velocity
###
### It may work with other types of servers, but the event system may not function properly
### In that case, McDis allows you to disable the default event system and implement a custom one

### start_command     :   Start command for the process, example: java -Xms6G -Xmx6G -Dfile.encoding=UTF-8 -jar launcher.jar nogui
### stop_command      :   Command to stop the process; if left blank, the process will be terminated abruptly
### relay_blacklist   :   List of terms; if contained in the log, it will not be sent to Discord

### Even with MCDReforged, set the .jar start command; McDis will edit the MCDReforged config
### 
### Recommended terms for the relay blacklist
### - 'Changed the block at'            # Prevents spam when pasting litematics or using WorldEdit
### - 'Successfully filled'             # Prevents spam when pasting litematics or using WorldEdit
### - '[WARN]:'                         # Prevents lag warning spam
### - '~[server-intermediary.jar:?]'    # Prevents spam when doing update suppression

### To apply the changes, you must restart McDis!!!

Bot Token: 
Panel ID:
Language: en
Backups: 3

Booleans:
  omit crash report relay : false
  upload overwrite        : false
  allow flask             : false

Flask:
  IP    : '0.0.0.0'
  Port  : 8000

Processes:
  Networks: 
    network 1:
      start_command: start
      stop_command: end
      relay_blacklist: 
        - 'example 1'
        - 'example 2'
        - 'example 3'

  Servers:
    server 1:
      start_command: start
      mcdreforged: false
      stop_command: stop
      relay_blacklist: 
        - 'example 1'
        - 'example 2'
        - 'example 3'
    
    server 2:
      start_command: start
      mcdreforged: false
      stop_command: stop
      relay_blacklist: 
        - 'example 1'
        - 'example 2'
        - 'example 3'